from __future__ import annotations

import logging
import re
import time
from typing import Dict, List, Optional, Tuple, Union

import pandas as pd
import pdfplumber

from app.core.config import settings

# -----------------------------
# pdfminer (text fallback)
# -----------------------------
try:
	from pdfminer.high_level import (
		extract_text as _pdfminer_extract_text,  # type: ignore
	)
except Exception:  # pragma: no cover - optional dependency
	_pdfminer_extract_text = None

# =======================
# Config / Logging
# =======================
STRICT_AMOUNT_REQUIRED = settings.STRICT_AMOUNT_REQUIRED

if STRICT_AMOUNT_REQUIRED:
	print('Strict amount checking is enabled')

logger = logging.getLogger('app.core.pdfToCSV')
if not logger.handlers:
	_level = settings.ENVIRONMENT.upper()
	_handler = logging.StreamHandler()
	_handler.setFormatter(
		logging.Formatter('[%(asctime)s] [%(levelname)s] pdfToCSV: %(message)s')
	)
	logger.addHandler(_handler)
	logger.setLevel(getattr(logging, _level, logging.INFO))


def _log_df(df: pd.DataFrame, label: str) -> None:
	try:
		shape = getattr(df, 'shape', None)
		cols = list(getattr(df, 'columns', []))
		logger.debug('%s: shape=%s, cols=%s', label, shape, cols)
		if isinstance(df, pd.DataFrame) and not df.empty:
			head = df.head(3).to_string(index=False)
			logger.debug('%s head(3):\n%s', label, head)
	except Exception as e:  # pragma: no cover - logging helper
		logger.debug('_log_df error: %s', e)


# =======================
# Normalization helpers
# =======================


def _norm(s: str) -> str:
	s = (s or '').replace('\u200b', '').strip().lower()
	s = re.sub(r'\s+', ' ', s)
	return s


def _defkey(s: str) -> str:
	return re.sub(r'[^a-zA-Zก-ฮ0-9]+', '', _norm(s))


def _cell_norm(x):
	if x is None or (isinstance(x, float) and pd.isna(x)):
		return None
	s = str(x).replace('\u200b', '').replace('\xa0', ' ')
	s = re.sub(r'\s+', ' ', s).strip()
	return s


# ============ Noise / Disclaimer filters ============
_DISCLAIMER_SNIPPETS = [
	# EN (disclaimer/call center/summary footers)
	(
		'this document is auto-generated by the system for the purpose of '
		'preliminary checking only'
	),
	'the bank does not guarantee the accuracy and completeness',
	'does not constitute any legal binding to the bank',
	'any legal binding to the bank in all respects',
	'scb call center',
	'total amount',
	'total items',
	# TH
	'เอกสารฉบับนี้ออกโดยระบบอัตโนมัติตามคําร้องขอของผู้ขอใช้บริการ',
	'เพื่อประโยชน์ในการตรวจสอบรายการในเบื้องต้นเท่านั้น',
	'ธนาคารจึงไม่รับรองความถูกต้องสมบูรณ์',
	'และไม่ก่อให้เกิดภาระผูกพันใดๆ ตามกฎหมาย',
	'ต่อธนาคารแต่อย่างใด',
	'ฝ่ายบริการลูกค้า ธนาคารไทยพาณิชย์',
	'ยอดรวมทั้งสิ้น',
	'รวมจำนวนรายการ',
]


def _is_disclaimer(s: str) -> bool:
	if not s:
		return False
	ns = re.sub(r'\s+', ' ', s).strip().lower()
	return any(snippet in ns for snippet in _DISCLAIMER_SNIPPETS)


# =======================
# Header map (TH/EN)
# =======================
HEADER_MAP: Dict[str, str] = {
	# datetime
	_defkey('วันที่-เวลา'): 'tx_datetime',
	_defkey('วันเวลา'): 'tx_datetime',
	_defkey('วันที่ เวลา'): 'tx_datetime',
	_defkey('วันที่/เวลา'): 'tx_datetime',
	_defkey('date/time'): 'tx_datetime',
	_defkey('datetime'): 'tx_datetime',
	_defkey('transaction date'): 'tx_datetime',
	# channel/code
	_defkey('ช่องทาง'): 'code_channel_raw',
	_defkey('รหัสช่องทาง'): 'code_channel_raw',
	_defkey('รายการ/ช่องทาง'): 'code_channel_raw',
	_defkey('รายการ'): 'code_channel_raw',
	_defkey('code/channel'): 'code_channel_raw',
	_defkey('channel'): 'code_channel_raw',
	_defkey('code channel'): 'code_channel_raw',
	_defkey('ประเภทธุรกรรม'): 'code_channel_raw',
	_defkey('ประเภท'): 'code_channel_raw',
	# debit
	_defkey('เดบิต'): 'debit_amount',
	_defkey('ถอน'): 'debit_amount',
	_defkey('withdrawal'): 'debit_amount',
	_defkey('debit'): 'debit_amount',
	_defkey('ลูกหนี้'): 'debit_amount',
	# credit
	_defkey('เครดิต'): 'credit_amount',
	_defkey('ฝาก'): 'credit_amount',
	_defkey('deposit'): 'credit_amount',
	_defkey('credit'): 'credit_amount',
	_defkey('เจ้าหนี้'): 'credit_amount',
	# balance
	_defkey('คงเหลือ'): 'balance_amount',
	_defkey('ยอดคงเหลือ'): 'balance_amount',
	_defkey('balance'): 'balance_amount',
	_defkey('available balance'): 'balance_amount',
	# description
	_defkey('รายละเอียด'): 'description_text',
	_defkey('บันทึกช่วยจำ'): 'description_text',
	_defkey('description/note'): 'description_text',
	_defkey('description'): 'description_text',
	_defkey('note'): 'description_text',
}
HEADER_MAP.update(
	{
		_defkey('date/time วันที่/เวลา'): 'tx_datetime',
		_defkey('code/channel รายการ/ช่องทาง'): 'code_channel_raw',
		_defkey('debit ลูกหนี้'): 'debit_amount',
		_defkey('credit เจ้าหนี้'): 'credit_amount',
		_defkey('balance ยอดคงเหลือ'): 'balance_amount',
		_defkey('description/note รายละเอียด/บันทึกช่วยจำ'): 'description_text',
	}
)


TARGET_COLS = [
	'tx_datetime',
	'code_channel_raw',
	'debit_amount',
	'credit_amount',
	'balance_amount',
	'description_text',
]


# =======================
# Heuristics / patterns
# =======================
_DT_PATTERNS = [
	re.compile(r'^\d{4}-\d{2}-\d{2}[ T]\d{1,2}:\d{2}$'),
	re.compile(r'^\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\s+\d{1,2}:\d{2}$'),
	re.compile(r'^\d{1,2}\s+[A-Za-z]{3}\s+\d{4}\s+\d{1,2}:\d{2}$'),
]
_HEADER_NOISE_TERMS = [
	'account statement',
	'statement period',
	'page',
	'account no',
	'account type',
	'รายการเดินบัญชี',
	'บันทึกช่วยจำ',
	'เลขที่บัญชี',
	'ประเภทบัญชี',
	'วันที่',
	'หน้า',
	'savings',
	'current',
	'พร้อมบันทึกช่วยจํา',
	'รายการเดินบัญชี พร้อมบันทึกช่วยจํา',
]
_HEADER_NOISE_RE = re.compile(
	'|'.join([re.escape(x) for x in _HEADER_NOISE_TERMS]), re.IGNORECASE
)


_amount_clean = re.compile(r'[^0-9\.\-]+')


def _looks_tx_datetime(s: Optional[str]) -> bool:
	if not s:
		return False
	s = re.sub(r'\s+', ' ', str(s).strip())
	for pat in _DT_PATTERNS:
		if pat.match(s):
			return True
	if re.match(r'^\d{1,2}[/-]\d{1,2}[/-]\d{2,4}$', s):
		return True
	return False


def _is_tx_row(row: pd.Series) -> bool:
	dt = row.get('tx_datetime')
	desc = row.get('description_text') or ''
	chan = row.get('code_channel_raw') or ''
	joined = f'{(dt or "")} {(chan or "")} {(desc or "")}'.strip()

	if _HEADER_NOISE_RE.search(joined):
		return False
	if any(_is_disclaimer(str(v or '')) for v in (dt, desc, chan)):
		return False

	if not _looks_tx_datetime(str(dt) if dt is not None else None):
		return False

	if STRICT_AMOUNT_REQUIRED:
		has_amount = any(
			x is not None
			for x in (
				row.get('debit_amount'),
				row.get('credit_amount'),
				row.get('balance_amount'),
			)
		)
		return bool(has_amount)
	else:
		has_any = any(
			[
				any(
					x is not None
					for x in (
						row.get('debit_amount'),
						row.get('credit_amount'),
						row.get('balance_amount'),
					)
				),
				bool((chan or '').strip()),
				bool((desc or '').strip()),
			]
		)
		return has_any


def _to_float_or_none(x):
	if x is None:
		return None
	s = str(x).strip()
	if s == '' or s.lower() in {'-', 'na', 'none'}:
		return None

	# NEW: normalize เคสแยก token เป็นชิ้น ๆ
	# รวมช่องว่างรอบจุด/คอมม่า -> ให้เป็น "ติดกัน"
	s = re.sub(r'\s*\.\s*', '.', s)
	s = re.sub(r'\s*,\s*', ',', s)
	# วงเล็บติดเลข เช่น "( 100,000 )" -> "(100,000)"
	s = re.sub(r'\(\s*', '(', s)
	s = re.sub(r'\s*\)', ')', s)
	# เคสติดเครื่องหมายลบด้านท้าย เช่น "100,000-" -> "-100,000"
	if re.match(r'^\d[\d,]*-\s*$', s):
		s = '-' + s.rstrip('-').strip()

	neg = s.startswith('(') and s.endswith(')')
	s = s.replace('(', '').replace(')', '')
	s = s.replace('฿', '').replace(',', '').replace(' ', '')
	s = _amount_clean.sub('', s)  # เหลือเฉพาะ 0-9 . -

	if s in {'', '-', '.', '-.'}:
		return None
	try:
		v = float(s)
		return -v if neg else v
	except Exception:
		return None


# ---------- Thai/EN date helpers ----------
TH_MONTH = {
	'ม.ค.': 'Jan',
	'ก.พ.': 'Feb',
	'มี.ค.': 'Mar',
	'เม.ย.': 'Apr',
	'พ.ค.': 'May',
	'มิ.ย.': 'Jun',
	'ก.ค.': 'Jul',
	'ส.ค.': 'Aug',
	'ก.ย.': 'Sep',
	'ต.ค.': 'Oct',
	'พ.ย.': 'Nov',
	'ธ.ค.': 'Dec',
	'ม.ค': 'Jan',
	'ก.พ': 'Feb',
	'มี.ค': 'Mar',
	'เม.ย': 'Apr',
	'พ.ค': 'May',
	'มิ.ย': 'Jun',
	'ก.ค': 'Jul',
	'ส.ค': 'Aug',
	'ก.ย': 'Sep',
	'ต.ค': 'Oct',
	'พ.ย': 'Nov',
	'ธ.ค': 'Dec',
}


def _thai_date_to_iso(dt_str: str) -> str:
	import datetime as dt

	s = (dt_str or '').strip()
	m = re.search(r'(\d{1,2})\s+([ก-ฮ\.]+)\s+(\d{4})(?:\s+(\d{1,2}:\d{2}))?', s)
	if m:
		day, th_mon, year, hm = m.groups()
		year = int(year) - 543
		mon_en = TH_MONTH.get(th_mon.strip(), None)
		if mon_en:
			if not hm:
				hm = '00:00'
			try:
				d = dt.datetime.strptime(
					f'{day} {mon_en} {year} {hm}', '%d %b %Y %H:%M'
				)
				return d.strftime('%Y-%m-%d %H:%M')
			except Exception:
				pass
	m2 = re.match(r'^(\d{1,2})/(\d{1,2})/(\d{2,4})\s+(\d{1,2}):(\d{2})$', s)
	if m2:
		d, m, y, hh, mm = m2.groups()
		y = int(y)
		if y < 100:
			y += 2000 if y < 70 else 1900
		return f'{y:04d}-{int(m):02d}-{int(d):02d} {int(hh):02d}:{int(mm):02d}'
	return s


# ---------- header mapping (fuzzy) ----------


def _map_header_name(s: str) -> Optional[str]:
	key = HEADER_MAP.get(_defkey(s))
	if key:
		return key
	s2 = _norm(s)
	if any(k in s2 for k in ['date', 'เวลา', 'วันที่', 'datetime']):
		return 'tx_datetime'
	if any(k in s2 for k in ['code', 'channel', 'ช่องทาง', 'รายการ', 'ประเภทธุรกรรม']):
		return 'code_channel_raw'
	if any(k in s2 for k in ['debit', 'เดบิต', 'ถอน', 'ลูกหนี้']):
		return 'debit_amount'
	if any(k in s2 for k in ['credit', 'เครดิต', 'ฝาก', 'เจ้าหนี้']):
		return 'credit_amount'
	if any(k in s2 for k in ['balance', 'คงเหลือ', 'ยอดคงเหลือ']):
		return 'balance_amount'
	if any(k in s2 for k in ['description', 'note', 'รายละเอียด', 'บันทึก']):
		return 'description_text'
	return None


def _apply_header_map(cols: List[str]) -> List[str]:
	mapped = []
	for c in cols:
		c = str(c or '').replace('\n', ' ').strip()
		key = _map_header_name(c)
		mapped.append(key if key else _norm(c))
	return mapped


def _strip_or_none(x):
	return x.strip() if isinstance(x, str) else None


# ---------- merge duplicate mapped columns ----------
_date_only_re = re.compile(r'^\d{1,2}[/-]\d{1,2}[/-]\d{2,4}$')
_time_only_re = re.compile(r'^\d{1,2}:\d{2}$')


def _drop_columns_safe(df: pd.DataFrame, cols_to_drop: List[str]) -> pd.DataFrame:
	safe = [
		c
		for c in dict.fromkeys(cols_to_drop)
		if isinstance(c, str) and c != '' and c in df.columns
	]
	if not safe:
		return df
	try:
		return df.drop(columns=safe, errors='ignore')
	except Exception as e:  # pragma: no cover - safety fallback
		logger.debug(f'_drop_columns_safe fallback: {e} | trying column selection')
		keep = [c for c in df.columns if c not in safe]
		return df.loc[:, keep]


def _merge_duplicate_mapped_cols(df: pd.DataFrame) -> pd.DataFrame:
	cols = list(df.columns)
	dup_groups: Dict[str, List[int]] = {}
	for i, c in enumerate(cols):
		dup_groups.setdefault(c, []).append(i)

	for col, idxs in dup_groups.items():
		if len(idxs) <= 1:
			continue
		base = cols[idxs[0]]
		for j in idxs[1:]:
			other = df.iloc[:, j]
			if col == 'tx_datetime':

				def _join_dt(a, b):
					a = (None if pd.isna(a) else str(a).strip()) or None
					b = (None if pd.isna(b) else str(b).strip()) or None
					if _date_only_re.match(a or '') and _time_only_re.match(b or ''):
						return f'{a} {b}'
					if _date_only_re.match(b or '') and _time_only_re.match(a or ''):
						return f'{b} {a}'
					return a or b

				df[base] = [_join_dt(x, y) for x, y in zip(df[base], other)]
			else:
				df[base] = df[base].combine_first(other)
		drop_cols = [cols[i] for i in idxs[1:]]
		df = _drop_columns_safe(df, drop_cols)
		cols = list(df.columns)
	return df


# ---------- money & code-channel helpers ----------
_MONEY_RE = re.compile(
	r"""
   (?<!\d:)                           # ด้านซ้ายห้ามเป็น "เลขตามด้วยโคลอน" (กัน 10:)
   (?:
       [()\-]?\d{1,3}(?:,\d{3})+(?:\.\d{1,2})?   # มีคอมม่าเป็นหลักพัน เช่น 100,000.00
     | [()\-]?\d+\.\d{1,2}                        # มีทศนิยม เช่น 0.50, 25.00
     | [()\-]?\d{3,}                              # จำนวนเต็มตั้งแต่ 3 หลักขึ้นไป (กัน 00/10)
   )
   (?!:\d)                           # ด้านขวาห้ามเป็น ":เลข" (กัน :00)
   """,
	re.VERBOSE,
)


def _looks_money_token(t: str) -> bool:
	if not t:
		return False
	s = t.strip()
	if ':' in s:
		return False
	if _MONEY_RE.fullmatch(s):
		return True
	if re.fullmatch(r'\d{1,3}(?:,\d{3})+(?:\.\d{1,2})?', s):
		return True
	if re.fullmatch(r'\d+\.\d{1,2}', s):
		return True
	if re.fullmatch(r'\d{2,}', s):
		return True
	return False


_CODE_PAT = re.compile(r'\b[0-9A-Za-z]+(?:/[0-9A-Za-z]+)+\b')


def _clean_code_channel(s: Optional[str]) -> Optional[str]:
	if not s:
		return s
	ss = re.sub(r'\s+', ' ', str(s)).strip()
	parts = [p for p in ss.split() if not _looks_money_token(p)]
	ss2 = ' '.join(parts).strip()
	m = _CODE_PAT.search(ss2)
	if m:
		return m.group(0).upper()
	parts2 = [p for p in parts if not re.fullmatch(r'\d+(?:\.\d+)?', p)]
	return ' '.join(parts2).strip() or None


# ---------- description normalizer ----------
_DESC_LABELS = [r'\bdesc\b', r'\bdescription\b', r'รายละเอียด']
_NOTE_LABELS = [r'\bnote\b', r'บันทึก', r'บันทึกช่วยจำ', r'บันทึกช่วยจํา']
_DESC_NOTE_HINT_RE = re.compile(
	r'\b(?:desc|description|รายละเอียด|note|บันทึก|บันทึกช่วยจำ|บันทึกช่วยจํา)\b',
	re.IGNORECASE,
)


def _normalize_desc_note(s: Optional[str]) -> Optional[str]:
	if not s:
		return s
	txt = re.sub(r'\s+', ' ', str(s)).strip()
	if _is_disclaimer(txt):
		return None

	desc = None
	note = None
	mdesc = re.search(
		r'('
		+ '|'.join(_DESC_LABELS)
		+ r')\s*:?\s*(.+?)(?=('
		+ '|'.join(_NOTE_LABELS)
		+ r')\s*:|\Z)',
		txt,
		re.IGNORECASE,
	)
	if mdesc:
		desc = mdesc.group(2).strip(' -,:;')

	mnote = re.search(
		r'(' + '|'.join(_NOTE_LABELS) + r')\s*:?\s*(.+)$', txt, re.IGNORECASE
	)
	if mnote:
		note = mnote.group(2).strip(' -,:;')

	if desc or note:
		return f'DESC : {desc or "-"}  NOTE : {note or "-"}'
	return txt or None


def _looks_desc_line(s: str) -> bool:
	s2 = re.sub(r'\s+', ' ', s or '').strip()
	if not s2:
		return False
	if _is_disclaimer(s2):
		return False
	return bool(_DESC_NOTE_HINT_RE.search(s2))


def _sanitize_description(s: Optional[str], code: Optional[str]) -> Optional[str]:
	if not s:
		return s
	norm = _normalize_desc_note(s)
	if norm and ('DESC :' in norm or 'NOTE :' in norm):
		return norm
	txt = re.sub(r'\s+', ' ', str(s)).strip()
	parts = [p for p in txt.split() if not _looks_money_token(p)]
	code_up = (code or '').strip().upper()
	parts = [p for p in parts if p.upper() != code_up and not _CODE_PAT.fullmatch(p)]
	cleaned = ' '.join(parts).strip(' -*,.;:')
	if not re.search(r'[A-Za-zก-ฮ]', cleaned):
		return None
	if _looks_desc_line(cleaned):
		return cleaned
	return cleaned or None


# ----- DESC/NOTE extractors (block-level) -----
_DESC_ANY = r'(?:desc|description|รายละเอียด)'
_NOTE_ANY = r'(?:note|บันทึก|บันทึกช่วยจำ|บันทึกช่วยจํา)'


def _block_to_text(lines_block: List[List[dict]]) -> str:
	parts = []
	for ln in lines_block:
		parts.append(' '.join((t.get('text') or '') for t in ln))
	txt = '\n'.join(parts)
	return re.sub(r'\s+', ' ', txt).strip()


def _extract_desc_note_from_text(txt: Optional[str]) -> Optional[str]:
	if not txt:
		return None
	s = re.sub(r'\s+', ' ', str(txt)).strip()
	mdesc = re.search(
		rf'{_DESC_ANY}\s*:?\s*(.+?)(?={_NOTE_ANY}\s*:|$)', s, re.IGNORECASE
	)
	mnote = re.search(rf'{_NOTE_ANY}\s*:?\s*(.+)$', s, re.IGNORECASE)
	desc = mdesc.group(1).strip(' -,:;') if mdesc else None
	note = mnote.group(1).strip(' -,:;') if mnote else None
	if desc or note:
		return f'DESC : {desc or "-"}  NOTE : {note or "-"}'
	return None


def _extract_desc_note_from_block(lines_block: List[List[dict]]) -> Optional[str]:
	raw = _block_to_text(lines_block)
	return _extract_desc_note_from_text(raw)


# ---------- FIX: repair debit/credit/balance using balance deltas ----------


def _repair_amount_columns(df: pd.DataFrame) -> pd.DataFrame:
	if df.empty:
		return df
	df = df.copy()
	for i in df.index:
		d = df.at[i, 'debit_amount']
		c = df.at[i, 'credit_amount']
		b = df.at[i, 'balance_amount']
		present = [(d, 'debit'), (c, 'credit'), (b, 'balance')]
		vals = [(v, n) for v, n in present if v is not None and not pd.isna(v)]
		if len(vals) == 2 and (b is None or pd.isna(b)):
			(v1, n1), (v2, n2) = vals
			if v1 >= v2:
				bal_v, other_v, other_n = v1, v2, n2
			else:
				bal_v, other_v, other_n = v2, v1, n1
			df.at[i, 'balance_amount'] = float(bal_v)
			if other_n == 'debit':
				df.at[i, 'debit_amount'] = float(other_v)
				df.at[i, 'credit_amount'] = None
			else:
				df.at[i, 'credit_amount'] = float(other_v)
				df.at[i, 'debit_amount'] = None

	# sort by time (stable)
	try:
		order = pd.to_datetime(df['tx_datetime'], errors='coerce')
		df['_ord'] = order
		df = df.sort_values(['_ord', df.index.name or 'index'], kind='stable').drop(
			columns=['_ord']
		)
	except Exception:
		pass

	eps = 0.01

	# forward pass: use previous balance
	prev_b = None
	for i in df.index:
		d = df.at[i, 'debit_amount']
		c = df.at[i, 'credit_amount']
		b = df.at[i, 'balance_amount']

		if prev_b is not None:
			if pd.isna(b):
				if pd.notna(c) and pd.isna(d):
					b = prev_b + c
				elif pd.notna(d) and pd.isna(c):
					b = prev_b - d
				elif pd.notna(c) and pd.notna(d):
					cand_c = prev_b + c
					cand_d = prev_b - d
					if cand_c >= 0 and (
						cand_d < 0 or abs(cand_c - prev_b) <= abs(cand_d - prev_b)
					):
						b = cand_c
						d = None
					else:
						b = cand_d
						c = None
			else:
				delta = b - prev_b
				if pd.isna(d) and pd.isna(c):
					if delta > eps:
						c = delta
					elif delta < -eps:
						d = -delta
				elif pd.notna(d) and pd.notna(c):
					if abs(delta - c) <= eps:
						d = None
					elif abs(delta + d) <= eps:
						c = None
					else:
						if delta > 0:
							c, d = abs(delta), None
						elif delta < 0:
							d, c = abs(delta), None
				else:
					if pd.notna(c) and delta < -eps:
						d, c = c, None
					elif pd.notna(d) and delta > eps:
						c, d = d, None

			df.at[i, 'debit_amount'] = None if pd.isna(d) else float(d)
			df.at[i, 'credit_amount'] = None if pd.isna(c) else float(c)
			df.at[i, 'balance_amount'] = None if pd.isna(b) else float(b)

			if pd.notna(df.at[i, 'balance_amount']):
				prev_b = df.at[i, 'balance_amount']
		else:
			if pd.notna(b):
				prev_b = b

	# backward pass: use next balance (fix leading rows with unknown prev)
	next_b = None
	for i in reversed(df.index.tolist()):
		d = df.at[i, 'debit_amount']
		c = df.at[i, 'credit_amount']
		b = df.at[i, 'balance_amount']

		if next_b is not None:
			if pd.isna(b):
				if pd.notna(c) and pd.isna(d):
					b = next_b - c
				elif pd.notna(d) and pd.isna(c):
					b = next_b + d
			else:
				delta_to_next = next_b - b
				if pd.isna(d) and pd.isna(c):
					if delta_to_next > eps:
						c = delta_to_next
					elif delta_to_next < -eps:
						d = -delta_to_next

			df.at[i, 'debit_amount'] = None if pd.isna(d) else float(d)
			df.at[i, 'credit_amount'] = None if pd.isna(c) else float(c)
			df.at[i, 'balance_amount'] = None if pd.isna(b) else float(b)

		if pd.notna(df.at[i, 'balance_amount']):
			next_b = df.at[i, 'balance_amount']

	return df


# ---------- standardize DataFrame ----------


def _standardize_df(df: pd.DataFrame) -> pd.DataFrame:
	t0 = time.time()
	df = df.copy()
	try:
		# pandas 2.2+
		df = df.map(_cell_norm)  # type: ignore[attr-defined]
	except AttributeError:
		df = df.applymap(_cell_norm)
	_log_df(df, 'raw-in')

	df.columns = _apply_header_map([str(c) for c in df.columns])
	df = _merge_duplicate_mapped_cols(df)
	_log_df(df, 'after-merge-dup')

	for col in TARGET_COLS:
		if col not in df.columns:
			df[col] = None
	df = df[TARGET_COLS]
	_log_df(df, 'after-reindex-targets')

	df['tx_datetime'] = df['tx_datetime'].map(_cell_norm)

	for c in ('debit_amount', 'credit_amount', 'balance_amount'):
		df[c] = df[c].map(_to_float_or_none)
	_log_df(df, 'after-amount-cast')

	for tcol in ('tx_datetime', 'code_channel_raw', 'description_text'):
		df[tcol] = df[tcol].apply(_strip_or_none)

	df['tx_datetime'] = df['tx_datetime'].apply(
		lambda s: _thai_date_to_iso(s) if isinstance(s, str) else s
	)
	_log_df(df, 'after-date-iso')

	# ตัด Disclaimer ทั้งแถว
	before = len(df)
	df = df[~df.apply(lambda r: any(_is_disclaimer(str(v or '')) for v in r), axis=1)]
	logger.debug(f'filter disclaimer rows: {before} -> {len(df)}')

	# ตัดแถว "ยอดยกมา"
	desc_series = df['description_text'].fillna('')
	before = len(df)
	mask_bf = desc_series.str.contains('balance brought forward', case=False)
	mask_th = desc_series.str.contains('ยอดคง.*ยกมา', case=False)
	df = df[~(mask_bf | mask_th)]
	logger.debug(f'filter brought-forward: {before} -> {len(df)}')

	# ฟิลเตอร์เฉพาะแถวที่เหมือนธุรกรรมจริง
	if not df.empty:
		before = len(df)
		df = df[df.apply(_is_tx_row, axis=1)]
		logger.debug(f'filter tx rows: {before} -> {len(df)}')
	_log_df(df, 'after-filter-tx-rows')

	# ซ่อมจำนวนเงิน/ยอดคงเหลือ
	df = _repair_amount_columns(df)

	# ทำความสะอาด code & description
	df['code_channel_raw'] = df['code_channel_raw'].map(_clean_code_channel)
	df['description_text'] = [
		_sanitize_description(d, c)
		for d, c in zip(df['description_text'], df['code_channel_raw'])
	]

	before = len(df)
	df = df[~(df['tx_datetime'].isna() & df['description_text'].isna())].reset_index(
		drop=True
	)
	logger.debug(f'filter blank rows: {before} -> {len(df)}')

	if not df.empty:
		before = len(df)
		df = df.drop_duplicates(subset=TARGET_COLS, keep='first').reset_index(drop=True)
		logger.debug(f'drop_duplicates: {before} -> {len(df)}')

	logger.debug(f'_standardize_df took {time.time() - t0:.3f}s')
	return df


# ---------- table extraction ----------
TABLE_SETTING_CANDIDATES = [
	dict(
		vertical_strategy='lines',
		horizontal_strategy='lines',
		text_x_tolerance=2,
		text_y_tolerance=2,
		intersection_x_tolerance=5,
		intersection_y_tolerance=5,
		snap_x_tolerance=2,
		snap_y_tolerance=2,
		join_tolerance=2,
		edge_min_length=40,
	),
	dict(
		vertical_strategy='text',
		horizontal_strategy='text',
		text_x_tolerance=2,
		text_y_tolerance=2,
	),
	dict(
		vertical_strategy='lines',
		horizontal_strategy='text',
		text_x_tolerance=2,
		text_y_tolerance=2,
	),
	dict(
		vertical_strategy='text',
		horizontal_strategy='lines',
		text_x_tolerance=2,
		text_y_tolerance=2,
	),
]


def _extract_tables_with_pdfplumber(
	file_obj, password: Optional[str]
) -> List[pd.DataFrame]:
	frames: List[pd.DataFrame] = []
	with pdfplumber.open(file_obj, password=password) as pdf:
		for page in pdf.pages:
			tables_all: List[List[List[str]]] = []
			for ts in TABLE_SETTING_CANDIDATES:
				try:
					tables = page.extract_tables(table_settings=ts) or []
					tables_all.extend(tables)
				except Exception:
					continue
			for tbl in tables_all:
				if not tbl or not any(tbl):
					continue
				header_idx = 0
				for i, row in enumerate(tbl[:5]):
					if any((str(x or '').strip() for x in row)):
						header_idx = i
						break
				header_raw = [str(x or '').strip() for x in tbl[header_idx]]
				next_row = tbl[header_idx + 1] if header_idx + 1 < len(tbl) else None
				header = [str(x or '').strip() for x in header_raw]
				body_start = header_idx + (2 if next_row else 1)
				body = [
					r
					for r in tbl[body_start:]
					if any((str(x or '').strip() for x in r))
				]
				if not body:
					continue
				try:
					df = pd.DataFrame(body, columns=header)
					df = _standardize_df(df)
					if not df.empty:
						frames.append(df)
				except Exception:
					pass
	return frames


# ---------- words-projection with SCB hard bounds ----------
HEADER_KEYS = [
	(
		'tx_datetime',
		['date', 'date/time', 'datetime', 'วันที่', 'เวลา', 'วันที่/เวลา', 'วัน/เวลา'],
	),
	(
		'code_channel_raw',
		[
			'code',
			'channel',
			'code/channel',
			'รายการ',
			'ช่องทาง',
			'รายการ/ช่องทาง',
			'ประเภทธุรกรรม',
		],
	),
	('debit_amount', ['debit', 'เดบิต', 'ลูกหนี้', 'ถอน', 'withdrawal']),
	('credit_amount', ['credit', 'เครดิต', 'เจ้าหนี้', 'ฝาก', 'deposit']),
	('balance_amount', ['balance', 'ยอดคงเหลือ', 'คงเหลือ']),
	(
		'description_text',
		['description', 'note', 'description/note', 'รายละเอียด', 'บันทึก', 'บันทึกช่วยจำ'],
	),
]


SCB_RELATIVE_BOUNDS = [
	('tx_datetime', 0.00, 0.17),
	('code_channel_raw', 0.17, 0.36),
	('debit_amount', 0.36, 0.48),
	('credit_amount', 0.48, 0.60),
	('balance_amount', 0.60, 0.74),
	('description_text', 0.74, 1.00),
]


def _categorize_header_token(txt: str) -> Optional[str]:
	t = _norm(txt)
	for key, variants in HEADER_KEYS:
		for v in variants:
			if _norm(v) in t:
				return key
	return None


def _infer_header_bounds_from_top(page) -> List[Tuple[str, float, float]]:
	words = page.extract_words(extra_attrs=['x0', 'x1', 'top', 'bottom']) or []
	if not words:
		return []
	H = page.height
	top_words = [w for w in words if w['top'] < H * 0.40]
	buckets: Dict[str, List[float]] = {}
	for w in top_words:
		key = _categorize_header_token(w['text'])
		if key:
			mid = (w['x0'] + w['x1']) / 2.0
			buckets.setdefault(key, []).append(mid)
	if len(buckets) < 3:
		return []
	centers = {k: sum(v) / len(v) for k, v in buckets.items()}
	ordered = sorted(centers.items(), key=lambda kv: kv[1])
	bounds: List[Tuple[str, float, float]] = []
	for i, (k, mid) in enumerate(ordered):
		left_mid = ordered[i - 1][1] if i > 0 else 0.0
		right_mid = ordered[i + 1][1] if i + 1 < len(ordered) else page.width
		x0 = (left_mid + mid) / 2 if i > 0 else 0.0
		x1 = (mid + right_mid) / 2 if i + 1 < len(ordered) else page.width
		bounds.append((k, x0, x1))
	return bounds


def _get_desc_x0(bounds: List[Tuple[str, float, float]], page_width: float) -> float:
	"""
	คืนค่า x0 ของคอลัมน์ description_text ถ้ามีใน bounds
	ถ้าไม่มี ให้ fallback เป็นสัดส่วนคงที่ (เช่น 0.74 ของความกว้างหน้า)
	"""
	for k, x0, x1 in bounds:
		if k == 'description_text':
			return float(x0)
	return page_width * 0.74  # fallback ตาม SCB_RELATIVE_BOUNDS


def _collect_desc_block_text(page, y0: float, y1: float, desc_x0: float) -> str:
	"""
	เก็บคำทั้งหมดในกรอบ (x >= desc_x0) และ y อยู่ระหว่าง [y0, y1]
	เรียงตาม y จากบนลงล่าง แล้วต่อเป็นข้อความบรรทัดเดียว (คั่นด้วยเว้นวรรค)
	หมายเหตุ: ใช้ extract_words เพื่อให้แม่นยำกว่า extract_text ในเคสคอลัมน์
	"""
	words = page.extract_words(extra_attrs=['x0', 'x1', 'top', 'bottom', 'text']) or []
	y_tol = 1.0
	lines: list[list[dict]] = []
	curr: list[dict] = []

	# เลือกเฉพาะคำที่อยู่ในโซน Description/Note
	tokens = [
		w
		for w in words
		if (
			(w['x0'] >= desc_x0 - 1)
			and (w['top'] >= y0 - y_tol)
			and (w['bottom'] <= y1 + y_tol)
		)
	]
	tokens.sort(key=lambda d: (d['top'], d['x0']))

	for w in tokens:
		if not curr or abs(curr[0]['top'] - w['top']) <= 4.5:
			curr.append(w)
		else:
			lines.append(curr)
			curr = [w]
	if curr:
		lines.append(curr)

	# ต่อ token เป็น text ต่อบรรทัด แล้วรวมทั้งบล็อก
	parts: list[str] = []
	for ln in lines:
		txt = ' '.join(t['text'] for t in ln if t.get('text')).strip()
		if txt:
			parts.append(txt)
	return ' '.join(parts).strip()


def _assign_cells_from_tokens(
	tokens: List[dict], bounds: List[Tuple[str, float, float]]
) -> Dict[str, str]:
	cells: Dict[str, str] = {k: '' for k, *_ in bounds}
	for tok in tokens:
		mid = (tok['x0'] + tok['x1']) / 2.0
		for k, x0, x1 in bounds:
			if x0 - 1 <= mid <= x1 + 1:
				text = (tok['text'] or '').strip()
				if k == 'code_channel_raw' and _looks_money_token(text):
					break
				if _is_disclaimer(text):
					break
				cells[k] = (cells[k] + ' ' + text).strip()
				break
	return cells


def _extract_by_words_projection(file_obj, password: Optional[str]) -> pd.DataFrame:
	rows_all: List[Dict] = []
	with pdfplumber.open(file_obj, password=password) as pdf:
		for page in pdf.pages:
			bounds = _infer_header_bounds_from_top(page)
			if not bounds:
				W = page.width
				bounds = [(k, W * a, W * b) for (k, a, b) in SCB_RELATIVE_BOUNDS]

			# x เริ่มของโซน Description/Note
			desc_x0 = _get_desc_x0(bounds, page.width)

			words = (
				page.extract_words(extra_attrs=['x0', 'x1', 'top', 'bottom', 'text'])
				or []
			)
			if not words:
				continue

			start_y = (
				min(
					[
						w['top']
						for w in words
						if re.search(r'\b\d{1,2}/\d{1,2}/\d{2,4}\b', w['text'])
					],
					default=page.height * 0.25,
				)
				- 4
			)

			y_tol = 4.5
			lines: List[List[dict]] = []
			for w in sorted(
				(t for t in words if t['top'] >= start_y),
				key=lambda d: (d['top'], d['x0']),
			):
				if not lines or abs(lines[-1][0]['top'] - w['top']) > y_tol:
					lines.append([w])
				else:
					lines[-1].append(w)

			i = 0
			while i < len(lines):
				line_tokens = lines[i]
				line_text = ' '.join(t['text'] for t in line_tokens).strip()
				if _HEADER_NOISE_RE.search(line_text.lower()) or _is_disclaimer(
					line_text
				):
					i += 1
					continue

				has_date_hint = bool(
					re.search(r'\b\d{1,2}/\d{1,2}/\d{2,4}\b', line_text)
					or re.search(r'\b\d{4}-\d{2}-\d{2}\b', line_text)
				)
				if not has_date_hint:
					i += 1
					continue

				base = _assign_cells_from_tokens(line_tokens, bounds)

				# ต่อบรรทัดถัด ๆ ไป
				j = i + 1
				while j < len(lines):
					nxt_tokens = lines[j]
					nxt_text = ' '.join(t['text'] for t in nxt_tokens).strip()
					if _is_disclaimer(nxt_text):
						j += 1
						continue
					if re.search(r'\b\d{1,2}/\d{1,2}/\d{2,4}\b', nxt_text) or re.search(
						r'\b\d{4}-\d{2}-\d{2}\b', nxt_text
					):
						break

					nxt_cells = _assign_cells_from_tokens(nxt_tokens, bounds)

					if base.get('tx_datetime') and _time_only_re.match(
						(nxt_cells.get('tx_datetime') or '').strip()
					):
						base['tx_datetime'] = (
							base['tx_datetime'] + ' ' + nxt_cells['tx_datetime']
						).strip()

					columns_to_fill = [
						'code_channel_raw',
						'debit_amount',
						'credit_amount',
						'balance_amount',
					]
					for k in columns_to_fill:
						if (not base.get(k)) and nxt_cells.get(k):
							base[k] = nxt_cells[k]

					dtxt = nxt_cells.get('description_text', '')
					if dtxt and not _is_disclaimer(dtxt):
						base['description_text'] = (
							base.get('description_text', '')
							+ ('\\n' if base.get('description_text') else '')
							+ dtxt
						).strip()
					elif _looks_desc_line(nxt_text):
						base['description_text'] = (
							base.get('description_text', '')
							+ ('\\n' if base.get('description_text') else '')
							+ nxt_text
						).strip()
					j += 1

				# ถ้ายังไม่มี description_text ให้ดูจากโซนขวาหลังเส้นแบ่ง (desc_x0)
				if not (base.get('description_text') or '').strip():
					y0 = lines[i][0]['top'] - 2
					y1 = lines[(j - 1 if j > i else i)][0]['bottom'] + 2
					raw_right = _collect_desc_block_text(page, y0, y1, desc_x0)
					blk_desc = _extract_desc_note_from_text(raw_right)
					if blk_desc and not _is_disclaimer(blk_desc):
						base['description_text'] = blk_desc

				# ทำความสะอาดก่อนบันทึก
				cc = _clean_code_channel(base.get('code_channel_raw'))
				desc = _sanitize_description(base.get('description_text'), cc)
				base['code_channel_raw'] = cc
				base['description_text'] = desc

				rows_all.append(
					{
						'tx_datetime': base.get('tx_datetime') or None,
						'code_channel_raw': base.get('code_channel_raw') or None,
						'debit_amount': base.get('debit_amount') or None,
						'credit_amount': base.get('credit_amount') or None,
						'balance_amount': base.get('balance_amount') or None,
						'description_text': base.get('description_text') or None,
					}
				)
				i = j

	if not rows_all:
		return pd.DataFrame(columns=TARGET_COLS)
	df = pd.DataFrame(rows_all, columns=TARGET_COLS)
	_log_df(df, 'words-projection raw')
	return _standardize_df(df)


# ---------- text fallback (gaps; last resort) ----------


def _extract_lines_with_pdfminer_or_plumber(
	file_obj, password: Optional[str]
) -> List[str]:
	lines: List[str] = []
	if _pdfminer_extract_text is not None:
		try:
			file_obj.seek(0)
			txt = _pdfminer_extract_text(file_obj) or ''
			tmp = [ln.strip() for ln in txt.splitlines() if ln.strip()]
			if tmp:
				lines = tmp
				file_obj.seek(0)
				return lines
		except Exception:
			pass

	file_obj.seek(0)
	with pdfplumber.open(file_obj, password=password) as pdf:
		for p in pdf.pages:
			text = p.extract_text() or ''
			for ln in text.splitlines():
				ln = ln.strip()
				if ln:
					lines.append(ln)
	file_obj.seek(0)
	return lines


def _parse_text_rows_by_gaps(lines: List[str]) -> pd.DataFrame:
	rows: List[Dict] = []
	pending: Optional[Dict] = None
	date_pat = re.compile(r'\b\d{1,2}/\d{1,2}/\d{2,4}\b')
	time_pat = re.compile(r'\b\d{1,2}:\d{2}\b')

	for ln in lines:
		if not ln:
			continue
		if _is_disclaimer(ln):
			continue

		if date_pat.search(ln):
			if pending:
				# สรุป DESC/NOTE ของ pending ก่อนหน้า
				if pending.get('description_text'):
					dn = _extract_desc_note_from_text(pending['description_text'])
					if dn:
						pending['description_text'] = dn
				rows.append(pending)
			pending = {
				'tx_datetime': None,
				'code_channel_raw': None,
				'debit_amount': None,
				'credit_amount': None,
				'balance_amount': None,
				'description_text': None,
			}
			dt = ln.strip()
			if time_pat.search(dt) and '/' in dt:
				mdt = re.search(r'\d{1,2}/\d{1,2}/\d{2,4}\s+\d{1,2}:\d{2}', dt)
				pending['tx_datetime'] = mdt.group(0) if mdt else dt
			else:
				date_only = re.search(r'\d{1,2}/\d{1,2}/\d{2,4}', dt).group(0)
				pending['tx_datetime'] = date_only
			continue

		if pending:
			if pending.get('tx_datetime') and (
				time_pat.search(ln) and ':' in ln and '/' not in ln
			):
				pending['tx_datetime'] = (
					f'{pending["tx_datetime"]} {time_pat.search(ln).group(0)}'
				)
				continue

			if any(
				k in _norm(ln)
				for k in [
					'x1',
					'x2',
					'enet',
					'pos',
					'sipi',
					'atm',
					'trf',
					'kb',
					'ktb',
					'scb',
				]
			):
				if not _is_disclaimer(ln):
					pending['code_channel_raw'] = (
						(pending.get('code_channel_raw') or '')
						+ (' ' if pending.get('code_channel_raw') else '')
						+ ln
					)

			raw_money_matches = [m for m in _MONEY_RE.finditer(ln)]

			def _not_time_fragment(m):
				start, end = m.span()
				left = ln[max(0, start - 2) : start]
				right = ln[end : min(len(ln), end + 2)]
				# กันรูปแบบ d:dd ทั้งซ้ายและขวา
				return not (re.match(r'\d:$', left) or re.match(r'^:\d', right))

			money = [m.group(0) for m in raw_money_matches if _not_time_fragment(m)]

			if money:
				for field in ('debit_amount', 'credit_amount', 'balance_amount'):
					if pending.get(field) is None and money:
						pending[field] = money.pop(0)
					if not money:
						break

			if not _is_disclaimer(ln):
				if pending.get('description_text'):
					pending['description_text'] = (
						pending['description_text'] + ' ' + ln
					).strip()
				else:
					pending['description_text'] = ln

	if pending:
		if pending.get('description_text'):
			dn = _extract_desc_note_from_text(pending['description_text'])
			if dn:
				pending['description_text'] = dn
		rows.append(pending)

	if not rows:
		return pd.DataFrame(columns=TARGET_COLS)
	df = pd.DataFrame(rows, columns=TARGET_COLS)
	return _standardize_df(df)


# =======================
# Custom Exceptions
# =======================
class StatementFormatUnsupported(Exception):
	"""Raised when the statement brand/layout is not supported (e.g., non-SCB)."""

	pass


class StatementParsingFailed(Exception):
	"""
	Raised when an intended brand (e.g., SCB) is detected but parsing yields no rows.
	"""

	pass


# =======================
# Brand detection
# =======================
_BRAND_HINTS = {
	'scb': [
		'siam commercial bank',
		'scb call center',
		'ธนาคารไทยพาณิชย์',
		'scb easy',
		'statement with memo',
		'รายการเดินบัญชี พร้อมบันทึกช่วยจำ',  # พบบ่อยในสเตทเมนต์ SCB
	],
}


def _detect_bank_brand(file_obj, password: Optional[str]) -> Optional[str]:
	"""
	อ่านข้อมูลหน้าแรกของไฟล์เพื่อระบุว่าเป็นสเตทเมนต์จากแบรนด์ใด
	คืนค่า: 'scb' หรือ None
	"""
	try:
		# ตรวจจับจาก pdfminer
		if _pdfminer_extract_text is not None:
			file_obj.seek(0)
			txt = _pdfminer_extract_text(file_obj) or ''
			norm = re.sub(r'\s+', ' ', txt).strip().lower()

			# คำสำคัญที่ใช้ในการตรวจจับ SCB
			scb_keywords = [
				'siam commercial bank',
				'scb call center',
				'ธนาคารไทยพาณิชย์',
				'scb easy',
				'statement with memo',
				'รายการเดินบัญชี พร้อมบันทึกช่วยจำ',
				'ธนาคารไทยพาณิชย์',
			]
			if any(keyword in norm for keyword in scb_keywords):
				file_obj.seek(0)
				return 'scb'
	except Exception as e:
		print(f'Error in pdfminer detection: {e}')
		pass

	# fallback ใช้ pdfplumber
	try:
		file_obj.seek(0)
		with pdfplumber.open(file_obj, password=password) as pdf:
			pages = pdf.pages[:2] if len(pdf.pages) >= 2 else pdf.pages
			buf = []
			for p in pages:
				t = p.extract_text() or ''
				buf.append(t)
			norm = re.sub(r'\s+', ' ', ' '.join(buf)).strip().lower()

			# คำสำคัญที่ใช้ในการตรวจจับ SCB
			scb_keywords = [
				'siam commercial bank',
				'scb call center',
				'ธนาคารไทยพาณิชย์',
				'scb easy',
				'statement with memo',
				'รายการเดินบัญชี พร้อมบันทึกช่วยจำ',
				'บันทึกช่วยจำ',
				'ธนาคาร',
				'เลขที่บัญชี',
				'ประเภทบัญชี',
				'ยอดคงเหลือ',
				'ถอน',
				'ฝาก',
				'debit',
				'credit',
				'บัญชี',
				'ธนาคารไทยพาณิชย์',
			]
			if any(keyword in norm for keyword in scb_keywords):
				file_obj.seek(0)
				return 'scb'
	except Exception as e:
		print(f'Error in pdfplumber detection: {e}')
		pass

	file_obj.seek(0)
	return None


# ---------- public API ----------
def extract_statement_df(
	file_obj, password: Optional[str] = None, return_meta: bool = False
) -> Union[pd.DataFrame, Tuple[pd.DataFrame, Dict]]:
	meta: Dict[str, Dict] = {'tables': {}, 'words': {}, 'fallback': {}}

	# -------- Brand gate --------
	brand = _detect_bank_brand(file_obj, password=password)
	if brand != 'scb':
		# ไม่ใช่ SCB หรือไม่รู้จักแบรนด์ -> ไม่รองรับ
		raise StatementFormatUnsupported(
			'This statement format is not supported. Please upload statements from SCB.'
		)

	# 1) tables-first
	file_obj.seek(0)
	frames = _extract_tables_with_pdfplumber(file_obj, password=password)
	meta['tables']['frames'] = len(frames)
	meta['tables']['rows_total'] = sum(len(f) for f in frames)
	if frames:
		out = pd.concat(
			[f for f in frames if isinstance(f, pd.DataFrame)], ignore_index=True
		)
		meta['tables']['rows_after_concat'] = len(out)
		if not out.empty:
			return (out, meta) if return_meta else out

	# 2) words-projection (robust + SCB hard bounds)
	file_obj.seek(0)
	df_words = _extract_by_words_projection(file_obj, password=password)
	meta['words']['rows'] = len(df_words)
	if not df_words.empty:
		return (df_words, meta) if return_meta else df_words

	# 3) text fallback (gaps + greedy)
	lines = _extract_lines_with_pdfminer_or_plumber(file_obj, password=password)
	meta['fallback']['lines'] = len(lines)
	df = _parse_text_rows_by_gaps(lines)
	meta['fallback']['rows'] = len(df)

	# ถึงจุดนี้ยังไม่มีข้อมูล แม้ตรวจพบว่าเป็น SCB -> แจ้ง parsing failed
	if df.empty:
		raise StatementParsingFailed(
			'ตรวจพบว่าเป็นสเตทเมนต์ SCB แต่ไม่พบธุรกรรมในไฟล์  '
			'โปรดตรวจสอบว่าเป็นไฟล์ที่สมบูรณ์, ไม่มีการสแกนเบี้ยว/เบลอ,'
			'มีหัวตาราง:'
			'วันที่/เวลา, รายการ/ช่องทาง, เดบิต, เครดิต, คงเหลือ, รายละเอียด/บันทึกช่วยจำ'
		)

	return (df, meta) if return_meta else df


def df_to_csv_bytes(df: pd.DataFrame) -> bytes:
	return df.to_csv(index=False).encode('utf-8')
